directories:
  output: release
  buildResources: electron/assets
appId: com.yourcompany.redio
productName: Redio
asarUnpack:
  - '**/*.node'
nsis:
  oneClick: false
  include: build/installer.nsh
files:
  - filter:
      - dist/**
      - server/**
      - electron/**
      - package.json
win:
  target:
    - nsis
  icon: node_modules/app-builder-lib/templates/icons/proton-native/proton-native.ico
mac:
  target:
    - dmg
  icon: electron/assets/icon.png
electronVersion: 30.5.1
